#Winlogbeat configuration
#Custom fields

fields_under_root: true
#fields.collector_node_id: node1
#fields.gl2_source_collector: ${sidecar.nodeId}
fields.LogType: "Desktop" # these extra fields are added to enrich data
fields.Location: "CERT.JE" # these extra fields are added to enrich data

#set registry file option for resuming and shutdown
winlogbeat.shutdown_timeout: 60s
winlogbeat.registry_file: C:/ProgramData/winlogbeat/.winlogbeat.yml

#Event Filtering
winlogbeat.event_logs:
  - name: Application
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 1000 # application crash
          - equals.event_id: 1001 # windows error reporting events

  - name: Security
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 1001 # The audit log was cleared
          - equals.event_id: 1102 # The security Log is now full
          - equals.event_id: 1104 # eventlog deleted
          - equals.event_id: 4624 # An account was successfully logged on
          - equals.event_id: 4625 # An account failed to log on
          - equals.event_id: 4634 # An account was logged off
          - equals.event_id: 4648 # A logon was attempted using explicit credentials
          - equals.event_id: 4657 # A registry value was modified
          - equals.event_id: 4661 # attempt to access an object
          - equals.event_id: 4662 # object permissions accessed
          - equals.event_id: 4672 # Special privileges assigned to new logon
          - equals.event_id: 4689 # A service was installed in the system
          - equals.event_id: 4698 # A scheduled task was created
          - equals.event_id: 4702 # A scheduled task was updated
          - equals.event_id: 4720 # A user account was created
          - equals.event_id: 4728 # A member was added to a security-enabled global group
          - equals.event_id: 4732 # A member was added to a security-enabled local group
          - equals.event_id: 4738 # A user account was changed
          - equals.event_id: 4740 # A user account was locked out
          - equals.event_id: 4756 # A member was added to a security-enabled universal group
          - equals.event_id: 4767 # A user account was unlocked
          - equals.event_id: 4768 # A kerberos authwentication ticket was requested
          - equals.event_id: 4769 # A Kerberos service ticket was requested
          - equals.event_id: 4771 # Kerberos pre-authentication failed
          - equals.event_id: 4771 # A Kerberos authentication ticket request failed.
          - equals.event_id: 4778 # user reconnected to RDP session
          - equals.event_id: 4779 # user disconnected from RDP session
          - equals.event_id: 4798 # A user's local group membership was enumerated.
          - equals.event_id: 4907 # Auditing settings on object were changed
          - equals.event_id: 5140 # Network share accessed
          - equals.event_id: 5141 # Directory service deleted
          - equals.event_id: 5142 # Network Share Created
          - equals.event_id: 5143 # Network share Modified
          - equals.event_id: 5144 # Network Share Deleted
          - equals.event_id: 6416 # external attached to system
          - equals.event_id: 9009 # user intiated RDP logoff

  - name: System
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 6 # Driver loaded
          - equals.event_id: 19 # WUA Update Installation
          - equals.event_id: 104 # Event Log was Cleared
          - equals.event_id: 219 # Failed Kernel Driver Loading
          - equals.event_id: 1125 # Internal Error
          - equals.event_id: 1126 # Generic Internal Error
          - equals.event_id: 1129 # Group Policy Application Failed due to Connectivity
          - equals.event_id: 7000 # Service Start failure
          - equals.event_id: 7024 # Service terminated
          - equals.event_id: 7032 # Service stop
          - equals.event_id: 7033 # The Service Control Manager did not initialize successfully.
          - equals.event_id: 7034 # Service terminated unexpectantly
          - equals.event_id: 7045 # New windows service

  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 21 #rdp user successfully authenticated
          - equals.event_id: 22 # Remote Desktop Services: Shell start notification received
          - equals.event_id: 23 # RDP logoff
          - equals.event_id: 24 # rdp user has disconnected
          - equals.event_id: 24 # rdp user connection succeeded
          - equals.event_id: 39 # seession A has been disconnected from session b
          - equals.event_id: 40 # sessions A reason code B

  - name: Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 1149 # established connection to RDP server from client

  - name: Microsoft-Windows-Sysmon/Operational
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 1 # process create
          - equals.event_id: 2 # process terminate
          - equals.event_id: 3 # network connection
          - equals.event_id: 12 # Registry event create
          - equals.event_id: 13 # Registry event rename
          - equals.event_id: 14 # Registry event set
          - equals.event_id: 255 #sysmon error

  - name: Microsoft-Windows-PowerShell/Operational
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 4104 # Powershell script logging

    # Windows Defender standard
  - name: Microsoft-Windows-Windows Defender/Operational
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 1005 # MALWAREPROTECTION_SCAN_FAILED
          - equals.event_id: 1006 # MALWAREPROTECTION_MALWARE_DETECTED
          - equals.event_id: 1007 # MALWAREPROTECTION_MALWARE_ACTION_TAKEN
          - equals.event_id: 1008 # MALWAREPROTECTION_MALWARE_ACTION_FAILED
          - equals.event_id: 1009 # MALWAREPROTECTION_QUARANTINE_RESTORE
          - equals.event_id: 1012 # MALWAREPROTECTION_QUARANTINE_DELETE_FAILED
          - equals.event_id: 1015 # MALWAREPROTECTION_BEHAVIOR_DETECTED
          - equals.event_id: 1116 # MALWAREPROTECTION_STATE_MALWARE_DETECTED
          - equals.event_id: 1117 # MALWAREPROTECTION_STATE_MALWARE_ACTION_TAKEN
          - equals.event_id: 1118 # MALWAREPROTECTION_STATE_MALWARE_ACTION_FAILED
          - equals.event_id: 1119 # MALWAREPROTECTION_STATE_MALWARE_ACTION_CRITICALLY_FAILED
          - equals.event_id: 1120 # MALWAREPROTECTION_THREAT_HASH
          - equals.event_id: 2001 # MALWAREPROTECTION_SIGNATURE_UPDATE_FAILED
          - equals.event_id: 2003 # MALWAREPROTECTION_ENGINE_UPDATE_FAILED
          - equals.event_id: 5001 # MALWAREPROTECTION_RTP_DISABLED
          - equals.event_id: 5008 # MALWAREPROTECTION_ENGINE_FAILURE
          - equals.event_id: 5012 # MALWAREPROTECTION_ANTIVIRUS_DISABLED

  - name: Microsoft-Windows-TaskScheduler/Operational
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 100 #Task registration: Task registered in Task Scheduler.
          - equals.event_id: 101 #Task started: Task execution started.
          - equals.event_id: 102 #Task completed: Task execution completed.
          - equals.event_id: 106 #Task triggered by user: Task triggered manually by a user.
          - equals.event_id: 107 #Task triggered by time: Task triggered at a specific time according to the scheduled time configuration.
          - equals.event_id: 110 #Task triggered on idle: Task triggered when the system goes idle, based on the idle conditions specified in the task configuration.
          - equals.event_id: 111 #Task triggered on power: Task triggered when a specific power event occurs, such as the system being powered on or off.
          - equals.event_id: 140 #Task registration updated: Task registration was modified or updated in Task Scheduler.
          - equals.event_id: 200 #Task failed to start: Task failed to start execution.
          - equals.event_id: 201 #Task stopped: Task execution was stopped or terminated.
          - equals.event_id: 203 #Task terminated: Task execution was forcibly terminated.
          - equals.event_id: 301 #Task missed its start time: Task did not start execution at its scheduled time.
          - equals.event_id: 400 #Task registration deleted: Task registration was deleted from Task Scheduler.
          - equals.event_id: 404 #Task registration disabled: Task registration was disabled and will not be triggered for execution.
          - equals.event_id: 410 #Task registration enabled: Task registration was enabled and will be triggered for execution according to the configured schedule.
          - equals.event_id: 413 #Task suspended: Task execution was suspended or paused.
          - equals.event_id: 414 #Task resumed: Task execution was resumed after being suspended.

  - name: Microsoft-Windows-WMI-Activity/Operational # incorrect should be WMI
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 169 # wmi

  - name: Microsoft-Windows-WinRM/Operational # incorrect should be WMI
    level: critical, error, warning
    ignore_older: 48h
    processors:
      - drop_event.when.not.or:
          - equals.event_id: 6
          - equals.event_id: 169
          - equals.event_id: 169###todo
          - equals.event_id: 169
          - equals.event_id: 169
          - equals.event_id: 169
          - equals.event_id: 169
          - equals.event_id: 169
          - equals.event_id: 169

path:
  data: C:\Program Files\Graylog\sidecar\cache\winlogbeat\data
  logs: C:\Program Files\Graylog\sidecar\logs

#output
output.logstash:
  hosts: ["host:5044"]
# References
# https://ponderthebits.com/2018/02/windows-rdp-related-event-logs-identification-tracking-and-investigation/
# https://woshub.com/rdp-connection-logs-forensics-windows/
# https://github.com/nsacyber/Event-Forwarding-Guidance/blob/master/Events/RecommendedEvents.csv
# https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/appendix-l--events-to-monitor
# https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide

